spring.application.name=api-gw-logistica-contenedores
server.port=8081
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG
spring.cloud.gateway.httpserver.wiretap=false
spring.cloud.gateway.httpclient.wiretap=false


apunte-api-gw-tpi.url-microservicio-solicitudes=http://localhost:8082
apunte-api-gw-tpi.url-microservicio-rutas=http://localhost:8083
