##############################################
# APP CONFIG
##############################################
spring.application.name=api-gw-logistica-contenedores
server.port=8080

##############################################
# LOGGING DEBUG (Gateway + Security)
##############################################
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG

spring.cloud.gateway.httpserver.wiretap=false
spring.cloud.gateway.httpclient.wiretap=false

##############################################
# URL Microservicios
##############################################
apunte-api-gw-tpi.url-microservicio-solicitudes=http://localhost:8082
apunte-api-gw-tpi.url-microservicio-rutas=http://localhost:8083

##############################################
# OAUTH2 CLIENT (Keycloak)
##############################################
spring.security.oauth2.client.registration.keycloak.client-id=tpi-backend-client
spring.security.oauth2.client.registration.keycloak.client-secret=CLIENT_SECRET_AQUI
spring.security.oauth2.client.registration.keycloak.scope=openid,profile

#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/tpi-backend

##############################################
# RESOURCE SERVER (JWT validation)
##############################################
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/tpi-backend

##############################################
# SPRING CLOUD GATEWAY
##############################################
spring.cloud.gateway.default-filters[0]=TokenRelay

# Ruta 1: microservicio solicitudes
spring.cloud.gateway.routes[0].id=microservicio-solicitudes
spring.cloud.gateway.routes[0].uri=${apunte-api-gw-tpi.url-microservicio-solicitudes}
spring.cloud.gateway.routes[0].predicates[0]=Path=/solicitudes-app/**

# Ruta 2: microservicio rutas
spring.cloud.gateway.routes[1].id=microservicio-rutas
spring.cloud.gateway.routes[1].uri=${apunte-api-gw-tpi.url-microservicio-rutas}
spring.cloud.gateway.routes[1].predicates[0]=Path=/rutas-app/**
